<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rooms')->insert([
            [
                'category_id' =>6,
                'floor_number' => 0,
                'room_number' => 101,
                'is_booked' => null,
                'extra_remark' => null,
                'booked_date' => null,
                'guest_capacity' => null,
                'room_status' => null,
               ],
            [
            'category_id' => 3,
            'floor_number' => 0,
            'room_number' => 102,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
            ],
            [
                'category_id' => 3,
                'floor_number' => 0,
                'room_number' => 103,
                'is_booked' => null,
                'extra_remark' => null,
                'booked_date' => null,
                'guest_capacity' => null,
                'room_status' => null,
            ],
             [
                'category_id' => 3,
                'floor_number' => 0,
                'room_number' => 104,
                'is_booked' => null,
                'extra_remark' => null,
                'booked_date' => null,
                'guest_capacity' => null,
                'room_status' => null,
            ],

            [
                'category_id' => 3,
                'floor_number' => 0,
                'room_number' => 105,
                'is_booked' => null,
                'extra_remark' => null,
                'booked_date' => null,
                'guest_capacity' => null,
                'room_status' => null,
            ],


          [
            'category_id' => 3,
            'floor_number' => 0,
            'room_number' => 106,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' => 3,
            'floor_number' => 0,
            'room_number' => 107,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' => 3,
            'floor_number' => 0,
            'room_number' => 108,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' => 5,
            'floor_number' => 0,
            'room_number' => 109,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 110,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 111,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 112,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 113,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 114,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 0,
            'room_number' => 115,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 0,
            'room_number' => 116,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 117,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 118,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 119,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 120,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 121,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 122,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 123,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 124,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 125,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 126,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 127,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 128,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 0,
            'room_number' => 129,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 0,
            'room_number' => 130,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>2,
            'floor_number' => 0,
            'room_number' => 131,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 0,
            'room_number' => 132,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 201,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 202,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 203,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 204,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 205,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 206,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 207,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 208,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 1,
            'room_number' => 209,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 210,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 211,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 1,
            'room_number' => 212,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 213,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 214,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 215,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 216,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 217,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 218,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 219,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 220,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 221,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 222,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 223,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 224,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 225,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 226,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>2,
            'floor_number' => 1,
            'room_number' => 227,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 228,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 229,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 1,
            'room_number' => 230,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>2,
            'floor_number' => 1,
            'room_number' => 231,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>1,
            'floor_number' => 1,
            'room_number' => 232,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

           [
            'category_id' =>3,
            'floor_number' => 1,
            'room_number' => 233,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>2,
            'floor_number' => 1,
            'room_number' => 234,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>2,
            'floor_number' => 1,
            'room_number' => 235,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 301,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 302,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 303,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 304,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 305,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 306,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 307,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 308,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 309,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 310,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 2,
            'room_number' => 311,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 312,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 313,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 314,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 315,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 316,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 317,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 318,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 319,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 320,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 321,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 322,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 323,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 324,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' =>2,
            'room_number' => 325,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 2,
            'room_number' => 326,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 2,
            'room_number' => 327,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 401,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 402,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 403,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 404,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 3,
            'room_number' => 405,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 406,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 407,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 408,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 409,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 410,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>6,
            'floor_number' => 3,
            'room_number' => 411,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 412,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 413,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 414,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 415,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 416,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 417,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 418,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 419,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 420,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 421,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 422,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 423,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>4,
            'floor_number' => 3,
            'room_number' => 424,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],
           [
            'category_id' =>5,
            'floor_number' => 3,
            'room_number' => 425,
            'is_booked' => null,
            'extra_remark' => null,
            'booked_date' => null,
            'guest_capacity' => null,
            'room_status' => null,
           ],

        ]);
    }
}
